### ISSUE TITLE
Desarrollar funcionamiento del registro de usuario

### ISSUE THREAD

**Issue by ezealavar** [kuruklg/repo-tpFinal#10]
- Crear entity usuario
- Crear repositorio con el metodo save()
- Crear controller con la ruta POST /registro para crear un nuevo usuario
- Crear service con el metodo "crearUsuario()"
- Crear las interfaces necesarias

**Comment by kuruklg** [comment]
Se realizo la creación de todos los paquetes, clases e interfaces para el funcionamiento de los registros de usuario.
